apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: operatorgroup
spec:
  targetNamespaces:
  - restapi-mongodb
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: my-percona-server-mongodb-operator
  namespace: restapi-mongodb
spec:
  channel: stable
  name: percona-server-mongodb-operator
  source: operatorhubio-catalog
  sourceNamespace: olm
